//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\advent-of-code-2021\Advent Of Code\2022\Monkey in the Middle\Monkey.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MonkeyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMonkeyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyNumber([NotNull] MonkeyParser.MonkeyNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyProgram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyProgram([NotNull] MonkeyParser.MonkeyProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyDefinitions([NotNull] MonkeyParser.MonkeyDefinitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyDefinition([NotNull] MonkeyParser.MonkeyDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyHeader([NotNull] MonkeyParser.MonkeyHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyStartingItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyStartingItems([NotNull] MonkeyParser.MonkeyStartingItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItems([NotNull] MonkeyParser.ItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem([NotNull] MonkeyParser.ItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyOperation([NotNull] MonkeyParser.MonkeyOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyOperand([NotNull] MonkeyParser.MonkeyOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyTest([NotNull] MonkeyParser.MonkeyTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyTestCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyTestCondition([NotNull] MonkeyParser.MonkeyTestConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.monkeyTestConditionDivisor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonkeyTestConditionDivisor([NotNull] MonkeyParser.MonkeyTestConditionDivisorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.trueAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrueAction([NotNull] MonkeyParser.TrueActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonkeyParser.falseAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFalseAction([NotNull] MonkeyParser.FalseActionContext context);
}
