//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\advent-of-code-2021\Advent Of Code\2022\Monkey in the Middle\Monkey.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class MonkeyLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, NONZERODIGIT=12, DIGIT=13, NUMBER=14, WORD=15, WHITESPACE=16, 
		NEWLINE=17, WHITEJUNK=18, OPERATOR=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "INPUTSTART", "CD", "LOWERCASE", "UPPERCASE", "NONZERODIGIT", 
		"DIGIT", "NUMBER", "WORD", "WHITESPACE", "NEWLINE", "WHITEJUNK", "OPERATOR"
	};


	public MonkeyLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MonkeyLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Monkey'", "':'", "'Starting items:'", "','", "'Operation: new ='", 
		"'old'", "'Test'", "'divisible'", "'by'", "'If true: throw to monkey'", 
		"'If false: throw to monkey'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"NONZERODIGIT", "DIGIT", "NUMBER", "WORD", "WHITESPACE", "NEWLINE", "WHITEJUNK", 
		"OPERATOR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Monkey.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MonkeyLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\xDA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\a', '\x13', '\xB6', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'\xB9', '\v', '\x13', '\x3', '\x14', '\x3', '\x14', '\x6', '\x14', '\xBD', 
		'\n', '\x14', '\r', '\x14', '\xE', '\x14', '\xBE', '\x3', '\x15', '\x6', 
		'\x15', '\xC2', '\n', '\x15', '\r', '\x15', '\xE', '\x15', '\xC3', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x5', '\x16', '\xC9', '\n', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x6', '\x16', '\xCD', '\n', '\x16', '\r', 
		'\x16', '\xE', '\x16', '\xCE', '\x3', '\x17', '\x3', '\x17', '\x6', '\x17', 
		'\xD3', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xD4', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x2', '\x2', '\x19', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\x2', '\x1B', '\x2', '\x1D', '\x2', '\x1F', '\x2', '!', '\xE', '#', '\xF', 
		'%', '\x10', '\'', '\x11', ')', '\x12', '+', '\x13', '-', '\x14', '/', 
		'\x15', '\x3', '\x2', '\a', '\x3', '\x2', '\x63', '|', '\x3', '\x2', '\x43', 
		'\\', '\x3', '\x2', '\x33', ';', '\x3', '\x2', '\x32', ';', '\x4', '\x2', 
		'\v', '\v', '\"', '\"', '\x2', '\xDE', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x31', '\x3', '\x2', '\x2', '\x2', '\x5', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\a', ':', '\x3', '\x2', '\x2', '\x2', '\t', 'J', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'L', '\x3', '\x2', '\x2', '\x2', '\r', 
		']', '\x3', '\x2', '\x2', '\x2', '\xF', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x66', '\x3', '\x2', '\x2', '\x2', '\x13', 'p', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 's', '\x3', '\x2', '\x2', '\x2', '\x17', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\xA8', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xAB', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\xAD', '\x3', '\x2', '\x2', '\x2', '!', '\xAF', 
		'\x3', '\x2', '\x2', '\x2', '#', '\xB1', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\'', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', ')', '\xC1', '\x3', '\x2', '\x2', '\x2', '+', '\xCC', '\x3', '\x2', 
		'\x2', '\x2', '-', '\xD2', '\x3', '\x2', '\x2', '\x2', '/', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\a', 'O', '\x2', '\x2', '\x32', 
		'\x33', '\a', 'q', '\x2', '\x2', '\x33', '\x34', '\a', 'p', '\x2', '\x2', 
		'\x34', '\x35', '\a', 'm', '\x2', '\x2', '\x35', '\x36', '\a', 'g', '\x2', 
		'\x2', '\x36', '\x37', '\a', '{', '\x2', '\x2', '\x37', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\x39', '\a', '<', '\x2', '\x2', '\x39', 
		'\x6', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', 'U', '\x2', '\x2', 
		';', '<', '\a', 'v', '\x2', '\x2', '<', '=', '\a', '\x63', '\x2', '\x2', 
		'=', '>', '\a', 't', '\x2', '\x2', '>', '?', '\a', 'v', '\x2', '\x2', 
		'?', '@', '\a', 'k', '\x2', '\x2', '@', '\x41', '\a', 'p', '\x2', '\x2', 
		'\x41', '\x42', '\a', 'i', '\x2', '\x2', '\x42', '\x43', '\a', '\"', '\x2', 
		'\x2', '\x43', '\x44', '\a', 'k', '\x2', '\x2', '\x44', '\x45', '\a', 
		'v', '\x2', '\x2', '\x45', '\x46', '\a', 'g', '\x2', '\x2', '\x46', 'G', 
		'\a', 'o', '\x2', '\x2', 'G', 'H', '\a', 'u', '\x2', '\x2', 'H', 'I', 
		'\a', '<', '\x2', '\x2', 'I', '\b', '\x3', '\x2', '\x2', '\x2', 'J', 'K', 
		'\a', '.', '\x2', '\x2', 'K', '\n', '\x3', '\x2', '\x2', '\x2', 'L', 'M', 
		'\a', 'Q', '\x2', '\x2', 'M', 'N', '\a', 'r', '\x2', '\x2', 'N', 'O', 
		'\a', 'g', '\x2', '\x2', 'O', 'P', '\a', 't', '\x2', '\x2', 'P', 'Q', 
		'\a', '\x63', '\x2', '\x2', 'Q', 'R', '\a', 'v', '\x2', '\x2', 'R', 'S', 
		'\a', 'k', '\x2', '\x2', 'S', 'T', '\a', 'q', '\x2', '\x2', 'T', 'U', 
		'\a', 'p', '\x2', '\x2', 'U', 'V', '\a', '<', '\x2', '\x2', 'V', 'W', 
		'\a', '\"', '\x2', '\x2', 'W', 'X', '\a', 'p', '\x2', '\x2', 'X', 'Y', 
		'\a', 'g', '\x2', '\x2', 'Y', 'Z', '\a', 'y', '\x2', '\x2', 'Z', '[', 
		'\a', '\"', '\x2', '\x2', '[', '\\', '\a', '?', '\x2', '\x2', '\\', '\f', 
		'\x3', '\x2', '\x2', '\x2', ']', '^', '\a', 'q', '\x2', '\x2', '^', '_', 
		'\a', 'n', '\x2', '\x2', '_', '`', '\a', '\x66', '\x2', '\x2', '`', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 'V', '\x2', '\x2', '\x62', 
		'\x63', '\a', 'g', '\x2', '\x2', '\x63', '\x64', '\a', 'u', '\x2', '\x2', 
		'\x64', '\x65', '\a', 'v', '\x2', '\x2', '\x65', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'g', '\a', '\x66', '\x2', '\x2', 'g', 'h', '\a', 
		'k', '\x2', '\x2', 'h', 'i', '\a', 'x', '\x2', '\x2', 'i', 'j', '\a', 
		'k', '\x2', '\x2', 'j', 'k', '\a', 'u', '\x2', '\x2', 'k', 'l', '\a', 
		'k', '\x2', '\x2', 'l', 'm', '\a', '\x64', '\x2', '\x2', 'm', 'n', '\a', 
		'n', '\x2', '\x2', 'n', 'o', '\a', 'g', '\x2', '\x2', 'o', '\x12', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'q', '\a', '\x64', '\x2', '\x2', 'q', 'r', '\a', 
		'{', '\x2', '\x2', 'r', '\x14', '\x3', '\x2', '\x2', '\x2', 's', 't', 
		'\a', 'K', '\x2', '\x2', 't', 'u', '\a', 'h', '\x2', '\x2', 'u', 'v', 
		'\a', '\"', '\x2', '\x2', 'v', 'w', '\a', 'v', '\x2', '\x2', 'w', 'x', 
		'\a', 't', '\x2', '\x2', 'x', 'y', '\a', 'w', '\x2', '\x2', 'y', 'z', 
		'\a', 'g', '\x2', '\x2', 'z', '{', '\a', '<', '\x2', '\x2', '{', '|', 
		'\a', '\"', '\x2', '\x2', '|', '}', '\a', 'v', '\x2', '\x2', '}', '~', 
		'\a', 'j', '\x2', '\x2', '~', '\x7F', '\a', 't', '\x2', '\x2', '\x7F', 
		'\x80', '\a', 'q', '\x2', '\x2', '\x80', '\x81', '\a', 'y', '\x2', '\x2', 
		'\x81', '\x82', '\a', '\"', '\x2', '\x2', '\x82', '\x83', '\a', 'v', '\x2', 
		'\x2', '\x83', '\x84', '\a', 'q', '\x2', '\x2', '\x84', '\x85', '\a', 
		'\"', '\x2', '\x2', '\x85', '\x86', '\a', 'o', '\x2', '\x2', '\x86', '\x87', 
		'\a', 'q', '\x2', '\x2', '\x87', '\x88', '\a', 'p', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'm', '\x2', '\x2', '\x89', '\x8A', '\a', 'g', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', '{', '\x2', '\x2', '\x8B', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8D', '\a', 'K', '\x2', '\x2', '\x8D', '\x8E', 
		'\a', 'h', '\x2', '\x2', '\x8E', '\x8F', '\a', '\"', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'h', '\x2', '\x2', '\x90', '\x91', '\a', '\x63', '\x2', 
		'\x2', '\x91', '\x92', '\a', 'n', '\x2', '\x2', '\x92', '\x93', '\a', 
		'u', '\x2', '\x2', '\x93', '\x94', '\a', 'g', '\x2', '\x2', '\x94', '\x95', 
		'\a', '<', '\x2', '\x2', '\x95', '\x96', '\a', '\"', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'v', '\x2', '\x2', '\x97', '\x98', '\a', 'j', '\x2', '\x2', 
		'\x98', '\x99', '\a', 't', '\x2', '\x2', '\x99', '\x9A', '\a', 'q', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', 'y', '\x2', '\x2', '\x9B', '\x9C', '\a', 
		'\"', '\x2', '\x2', '\x9C', '\x9D', '\a', 'v', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', 'q', '\x2', '\x2', '\x9E', '\x9F', '\a', '\"', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 'o', '\x2', '\x2', '\xA0', '\xA1', '\a', 'q', '\x2', '\x2', 
		'\xA1', '\xA2', '\a', 'p', '\x2', '\x2', '\xA2', '\xA3', '\a', 'm', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', 'g', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'{', '\x2', '\x2', '\xA5', '\x18', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', '&', '\x2', '\x2', '\xA7', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', '\x65', '\x2', '\x2', '\xA9', '\xAA', '\a', 
		'\x66', '\x2', '\x2', '\xAA', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAC', '\t', '\x2', '\x2', '\x2', '\xAC', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAE', '\t', '\x3', '\x2', '\x2', '\xAE', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xB0', '\t', '\x4', '\x2', '\x2', '\xB0', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\t', '\x5', '\x2', 
		'\x2', '\xB2', '$', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB7', '\x5', 
		'!', '\x11', '\x2', '\xB4', '\xB6', '\x5', '#', '\x12', '\x2', '\xB5', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '&', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBD', '\x5', '\x1D', '\xF', 
		'\x2', '\xBB', '\xBD', '\x5', '\x1F', '\x10', '\x2', '\xBC', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '(', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC2', '\t', '\x6', '\x2', '\x2', '\xC1', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\b', '\x15', '\x2', '\x2', '\xC6', '*', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC9', '\a', '\xF', '\x2', '\x2', '\xC8', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCD', '\a', '\f', '\x2', 
		'\x2', '\xCB', '\xCD', '\a', '\xF', '\x2', '\x2', '\xCC', '\xC8', '\x3', 
		'\x2', '\x2', '\x2', '\xCC', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xCF', ',', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD3', '\x5', '+', '\x16', '\x2', '\xD1', 
		'\xD3', '\x5', ')', '\x15', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', 
		'\x2', '\xD6', '\xD7', '\b', '\x17', '\x2', '\x2', '\xD7', '.', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\xD9', '\x4', ',', '-', '\x2', '\xD9', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\f', '\x2', '\xB7', '\xBC', '\xBE', '\xC3', 
		'\xC8', '\xCC', '\xCE', '\xD2', '\xD4', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
