//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\advent-of-code-2021\Advent Of Code\2022\7 Out Of Space\ConsoleInputOutput.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ConsoleInputOutputParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IConsoleInputOutputVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension([NotNull] ConsoleInputOutputParser.ExtensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.fileName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileName([NotNull] ConsoleInputOutputParser.FileNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.fileSize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileSize([NotNull] ConsoleInputOutputParser.FileSizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.fileDescriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileDescriptor([NotNull] ConsoleInputOutputParser.FileDescriptorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.directoryName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectoryName([NotNull] ConsoleInputOutputParser.DirectoryNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ConsoleInputOutputParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.commands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommands([NotNull] ConsoleInputOutputParser.CommandsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.cdUp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCdUp([NotNull] ConsoleInputOutputParser.CdUpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.lsCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLsCommand([NotNull] ConsoleInputOutputParser.LsCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.fileSizeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileSizeCommand([NotNull] ConsoleInputOutputParser.FileSizeCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.dirCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirCommand([NotNull] ConsoleInputOutputParser.DirCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.cdDown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCdDown([NotNull] ConsoleInputOutputParser.CdDownContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.cdCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCdCommand([NotNull] ConsoleInputOutputParser.CdCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleInputOutputParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] ConsoleInputOutputParser.CommandContext context);
}
